version: '3.8'
services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=raffleDB
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URI=${DB_URI}
      - PORT=${PORT}
    depends_on:
      - db
