version: '3.8'
services:
  db:
    image: mongo:latest
    volumes:
    - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=raffleDB
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URI=${DB_URI}
      - PORT=${PORT}
      - SESSION_SECRET=${SESSION_SECRET}

    depends_on:
      - db

volumes: 
  mongo_data:
    driver: local